### ISSUE TITLE
Bootloop when updating from 6.6.0 to 6.7.0

### ISSUE THREAD

**Issue by adamalfath** [platformio/platform-espressif32#1432]
I have proven working hardware and firmware, but when I do update the platform version it causing bootloop.
Here is what I observed so far:

- On 6.7.0 if I use my "full" program (~2.3MB) uploaded successfully but device will bootloop
- On 6.7.0 I use `erase_flash` and `verify_flash` from esptool, it's done without issue. Making sure it is not corrupted flash.
- On 6.7.0 if I upload simple blink program it works without bootloop
- Back to 6.6.0 my "full" program works normally

Here a snippet from platformio.ini that might be related, the rest are just libdeps. I configure the output to USB-CDC. I don't break out the UART0 pinout so at the moment I'm unable to log the boot message from there.

```
platform = espressif32
framework = arduino
board = esp32-c3-devkitm-1
board_build.partitions = huge_app.csv
board_build.filesystem = littlefs
build_flags = 
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
```

**Comment by adamalfath** [comment]
Using 6.8.1, USB is stable in boot mode and getting exception error message. On 6.7.0 the USB keep reconnecting.

The decoder showing:
```
Guru Meditation Error: Core  0 panic'ed (Store access fault). Exception was unhandled.

Core  0 register dump:
MEPC    : 0x42027898  RA      : 0x42027890  SP      : 0x3fca8850  GP      : 0x3fc92400
TP      : 0x3fba9c70  T0      : 0xffffffff  T1      : 0xffc3ffff  T2      : 0x00000001
S0/FP   : 0x3fc97090  S1      : 0x00000000  A0      : 0x00000001  A1      : 0xffffffff
A2      : 0x00000000  A3      : 0xfdffffff  A4      : 0x08000000  A5      : 0x00000010
A6      : 0x00000000  A7      : 0x04c4b400  S2      : 0x00000000  S3      : 0x00000000
S4      : 0x00000000  S5      : 0x00000000  S6      : 0x00000000  S7      : 0x00000000
S8      : 0x00000000  S9      : 0x00000000  S10     : 0x00000000  S11     : 0x00000000
T3      : 0x00000000  T4      : 0x0000000f  T5      : 0x003c0000  T6      : 0x00000003
MSTATUS : 0x00001881  MTVEC   : 0x40380001  MCAUSE  : 0x00000007  MTVAL   : 0x00000010
MHARTID : 0x00000000

Stack memory:
3fca8850: 0x00000000 0x3fc9c000 0x02625a00 0x00000001 0x00000000 0x3fc9c000 0x3fc97090 0x42027b0a
  #0  0x3fc97090 in ?? at src/display.cpp:3
  #1  0x42027b0a in TFT_eSPI::init(unsigned char) at lib/TFT_eSPI/TFT_eSPI.cpp:693
```

The information lead to more specific cause. I found discussion to similar problem here https://github.com/Bodmer/TFT_eSPI/issues/3384. From what I understand this might be related to `REG_SPI_BASE` which I notice differ from the known working core 2.0.14 (platform 6.6.0).

I'll close this issue as it more of an arduino core problem.
