### ISSUE TITLE
Can't use the feature/arduino-upstream branch

### ISSUE THREAD

**Issue by rob-deutsch** [platformio/platform-espressif32#606]
I am getting the following error...
```
speeduino % pio run
Processing esp32 (platform: https://github.com/platformio/platform-espressif32.git#feature/arduino-upstream; board: esp32dev; framework: arduino)
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Error: Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/platformio/__main__.py", line 109, in main
    cli()  # pylint: disable=no-value-for-parameter
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/platformio/commands/__init__.py", line 44, in invoke
    return super(PlatformioCLI, self).invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/platformio/commands/run/command.py", line 133, in cli
    process_env(
  File "/usr/local/lib/python3.9/site-packages/platformio/commands/run/command.py", line 175, in process_env
    result = {"env": name, "duration": time(), "succeeded": ep.process()}
  File "/usr/local/lib/python3.9/site-packages/platformio/commands/run/processor.py", line 70, in process
    p = PlatformFactory.new(self.options["platform"])
  File "/usr/local/lib/python3.9/site-packages/platformio/platform/factory.py", line 70, in new
    platform_cls = getattr(
AttributeError: module 'platformio.platform.platform' has no attribute 'PlatformPlatform'
```

When trying to use this platformio environment...
```
[env:esp32]
platform = https://github.com/platformio/platform-espressif32.git#feature/arduino-upstream
board = esp32dev
framework = arduino
```

Am I doing something wrong?

**Comment by rob-deutsch** [comment]
I deleted my `~/.platformio` folder and my development `.pio` folder and now it seems to work.

I don't know why/how, but at least it works now.
